name: smart-cart-backend
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.9
  - pip
  - pip:
    - fastapi==0.128.0
    - uvicorn[standard]
    - sqlalchemy
    - psycopg2-binary
    - python-multipart
    - boto3
    - mlflow>=3.0.0
    - pytest
    - black
    - isort
