name: pickle_backend
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.9
  - pip
  - pip:
    - fastapi==0.128.0
    - uvicorn[standard]
    - sqlalchemy
    - psycopg2-binary
    - python-multipart
    - boto3
    - mlflow>=3.0.0
    - pytest
    - black
    - isort
    - httpx==0.28.1
    - python-dotenv==1.2.1
    - numpy==2.4.1
