name: pickle_mlops
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - apache-airflow==2.10.4
    - mlflow>=3.0.0
    - boto3
    - psycopg2-binary
    - pandas
    - scikit-learn